# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.4"

Vagrant.configure("2") do |config|
  config.vm.define :zhangyue do |zhangyue|
    zhangyue.vm.hostname = "zhangyue"
    zhangyue.vm.box = "ubuntu/xenial64"
    zhangyue.vm.provider "virtualbox" do |v, override|
      v.memory = 2048
    end

    zhangyue.vm.provision "shell", inline: <<-SHELL
      # install docker-ce 18.09
      until apt-get update; do echo "Waiting apt-get for 3 seconds..."; sleep 3; done
      apt-get --no-install-recommends install curl apt-transport-https ca-certificates software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update
      apt-get --no-install-recommends install -y docker-ce=5:18.09.1~3-0~ubuntu-xenial docker-ce-cli=5:18.09.1~3-0~ubuntu-xenial containerd.io
    SHELL

    zhangyue.vm.provision "shell", inline: <<-SHELL
      # configring golang 1.12.6 environments
      GO_VERSION=1.12.6
      GOROOT=/opt/go
      GOPATH=/root/go
      apt-get install -y --no-install-recommends build-essential
      wget --progress=bar:force:noscroll https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz -O /tmp/go$GO_VERSION.linux-amd64.tar.gz
      tar xf /tmp/go$GO_VERSION.linux-amd64.tar.gz -C /opt/
      echo "export GOROOT=$GOROOT" >> ~/.bashrc
      echo "export GOPATH=$GOPATH" >> ~/.bashrc
      echo "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin" >> ~/.bashrc
      export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
      mkdir -p $GOPATH
      # prepare code for the vm
      ln -s -f /vagrant/src $GOPATH/src
      ln -s -f /vagrant/pkg $GOPATH/pkg
      ln -s -f /vagrant/bin $GOPATH/bin
    SHELL
    
    zhangyue.vm.provision "shell", inline: <<-SHELL
      # prepare for bash
      apt-get install python
      apt-get install jq
      apt-get install zsh
      chsh -s /bin/zsh
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      wget https://github.com/downloads/joelthelion/autojump/autojump_v21.1.2.tar.gz
      tar -xvf autojump_v21.1.2.tar.gz
      cd autojump_v21.1.2 && ./install.sh && cd ..
      rm -rf autojump_v21.1.2 && rm autojump_v21.1.2.tar.gz
      git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
      ~/.fzf/install --all
      # set up zshrc
      wget https://raw.githubusercontent.com/ZYecho/dotfiles/master/zsh/zshrc -O ~/.zshrc  
      source ~/.zshrc
    SHELL

  end
end
